# Generated by Django 2.2.12 on 2020-04-06 13:31

from django.db import migrations
import larvik.fields
import larvik.storage.local


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0002_auto_20200406_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioimage',
            name='file',
            field=larvik.fields.BioImageFileField(storage=larvik.storage.local.MediaStorage(), upload_to='bioimages', verbose_name='bioimage'),
        ),
    ]
