# Generated by Django 2.2.11 on 2020-03-30 17:43

from django.db import migrations
import larvik.fields
import larvik.storage.s3


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='store',
            field=larvik.fields.StoreFileField(blank=True, help_text='The location of the Array on the Storage', null=True, storage=larvik.storage.s3.ZarrStorage(), upload_to='', verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='store',
            field=larvik.fields.StoreFileField(blank=True, help_text='The location of the Array on the Storage', null=True, storage=larvik.storage.s3.ZarrStorage(), upload_to='', verbose_name='store'),
        ),
    ]
