# Generated by Django 2.2.12 on 2020-04-06 08:05

from django.db import migrations, models
import larvik.fields
import larvik.storage.s3


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20200403_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='dims',
            field=larvik.fields.DimsField(base_field=models.CharField(max_length=100), help_text='The arrays dimension', size=None),
        ),
        migrations.AlterField(
            model_name='representation',
            name='name',
            field=models.CharField(blank=True, help_text='Cleartext name', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='representation',
            name='shape',
            field=larvik.fields.ShapeField(base_field=models.IntegerField(), help_text='The arrays shape', size=None),
        ),
        migrations.AlterField(
            model_name='representation',
            name='signature',
            field=models.CharField(blank=True, help_text='The arrays unique signature', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='representation',
            name='store',
            field=larvik.fields.StoreFileField(blank=True, help_text='The location of the Array on the Storage System (S3 or Media-URL)', null=True, storage=larvik.storage.s3.ZarrStorage(), upload_to='zarr', verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='dims',
            field=larvik.fields.DimsField(base_field=models.CharField(max_length=100), help_text='The arrays dimension', size=None),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='name',
            field=models.CharField(blank=True, help_text='Cleartext name', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='shape',
            field=larvik.fields.ShapeField(base_field=models.IntegerField(), help_text='The arrays shape', size=None),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='signature',
            field=models.CharField(blank=True, help_text='The arrays unique signature', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='store',
            field=larvik.fields.StoreFileField(blank=True, help_text='The location of the Array on the Storage System (S3 or Media-URL)', null=True, storage=larvik.storage.s3.ZarrStorage(), upload_to='zarr', verbose_name='store'),
        ),
    ]
