# Generated by Django 2.2.12 on 2020-04-06 13:31

from django.db import migrations
import larvik.fields
import larvik.storage.local


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_auto_20200406_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='store',
            field=larvik.fields.StoreFileField(blank=True, help_text='The location of the Array on the Storage System (S3 or Media-URL)', null=True, storage=larvik.storage.local.ZarrStorage(), upload_to='zarr', verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='store',
            field=larvik.fields.StoreFileField(blank=True, help_text='The location of the Array on the Storage System (S3 or Media-URL)', null=True, storage=larvik.storage.local.ZarrStorage(), upload_to='zarr', verbose_name='store'),
        ),
    ]
