# Generated by Django 2.2.12 on 2020-04-08 10:58

from django.db import migrations, models
import larvik.fields
import larvik.storage.s3
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_auto_20200406_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='unique',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='transformation',
            name='unique',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='representation',
            name='store',
            field=larvik.fields.StoreFileField(blank=True, help_text='The location of the Array on the Storage System (S3 or Media-URL)', null=True, storage=larvik.storage.s3.ZarrStorage(), upload_to='zarr', verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='store',
            field=larvik.fields.StoreFileField(blank=True, help_text='The location of the Array on the Storage System (S3 or Media-URL)', null=True, storage=larvik.storage.s3.ZarrStorage(), upload_to='zarr', verbose_name='store'),
        ),
    ]
